fix: Check that storageClient is not nil before getting GCS bucket
GoogleCloudPlatform/terraform-google-conversion pull request #2960
Opened 2024-10-18 20:17 UTC by jalseth

When running the conversion in offline mode, this client is nil which causes the converter to panic.

2024-10-18 20:55 UTC, melinath commented
@zli82016 would you want to take this? Let me know if you need anything!

2024-10-18 21:09 UTC, zli82016 commented
> @zli82016 would you want to take this? Let me know if you need anything!

Sure, I will take this.

2024-10-21 21:09 UTC, zli82016 commented
/gcbrun

2024-10-22 17:11 UTC, zli82016 commented
The tgc-pull-license-check  failure is not related to this PR, as it failed for a while in https://github.com/GoogleCloudPlatform/terraform-google-conversion/

2024-10-23 23:10 UTC, zli82016 commented
This file is generated from [magic modules](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/tgc/ancestrymanager/ancestrymanager.go#L367). Can you please make change [there](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/tgc/ancestrymanager/ancestrymanager.go#L367)? Thanks.

2024-10-24 19:16 UTC, zli82016 requested changes
Move the change to magic modules.

2024-11-01 23:17 UTC, jalseth commented
Done: https://github.com/GoogleCloudPlatform/magic-modules/pull/12231

2024-11-01 23:17 UTC, closed without merging